

class NextClassException(Exception):
    pass


class PreviousClassException(Exception):
    pass